CREATE OR REPLACE TASK DATA_UPDATE_TASK
  WAREHOUSE = CRYPTO_WH
  SCHEDULE = 'USING CRON 0 0 * * * UTC'
WHEN
  SYSTEM$STREAM_HAS_DATA('RAW.CRYPTO_DATA_STREAM')
AS
  CALL DATA_UPDATE();  

CREATE OR REPLACE TASK DATA_HARMONIZATION_TASK
  WAREHOUSE = CRYPTO_WH
  AFTER DATA_UPDATE_TASK
AS
  CALL HARMONIZED.DATA_HARMONIZATION();  

ALTER TASK DATA_UPDATE_TASK RESUME;

ALTER TASK DATA_HARMONIZATION_TASK RESUME;

SHOW TASKS IN SCHEMA CRYPTO_DB.RAW;

